version: '3'
services:
  backend-instagram:
    build: ./backend
    container_name: instagram-backend
    restart: always
    ports:
      - 5000:5000
    command: sh -c "python3 main.py"
  frontend-instagram:
    build: .
    container_name: instagram-frontend
    restart: always
    ports:
      - 4173:4173
    command: sh -c "npm run preview"
